version: "3.1"
nlu:
- intent: travel/surrounging_scenic_spots
  examples: |
    - 神武门周边都有哪些好玩的地方啊？
- intent: travel/time_to_visit
  examples: |
    - 知道东岳庙可以玩多久不？
- intent: affirm
  examples: |
    - 正确
- intent: mood_great
  examples: |
    - 好
- intent: mood_unhappy
  examples: |
    - 难受
- intent: bot_challenge
  examples: |
    - 你是机器人吗？
- intent: bot_first_scene
  examples: |
    - hello world
- intent: opening_hours
  examples: |
    - 这个景点一般啥时候开放啊
- intent: surrounging_scenic_spots
  examples: |
    - 周边都有哪些好玩的地方啊
- intent: bot_first_slot
  examples: |
    - 我想知道[slot](fslot)的信息
    - 测试slot
- intent: information
  examples: |
    - 知道[排云殿](location_slot)吗
    - 你知道[百雅轩798艺术中心](location_slot)吗
    - 知道[排云殿](location_slot)吗？
- intent: location
  examples: |
    - 你好，可以帮我查一下[神武门](location_slot)在哪里吗
    - 在哪里呢
    - [神武门](location_slot)在哪儿呢
- intent: ticket
  examples: |
    - 知道门票多少钱吗
    - 不过去这里我不知道需不需要门票
    - 那里需要门票吗
- intent: time_to_visit
  examples: |
    - 它的游玩时间要多久
    - 能玩多久
    - 知道这里可以玩多久不
    - 能玩多久啊
- intent: deny
  examples: |
    - 否定
    - 我不同意你的观点
    - 不是的
    - 不行
    - 不同意
    - 不好
    - 拒绝
    - no
    - 不认同
    - 不是这样子的
    - 不可以
- intent: greet
  examples: |
    - hi
    - 在不在
    - 你好啊
    - 嗨
    - 见到你很高兴
    - hello hello
    - 喂喂
    - 哈喽哈喽
    - 上午好
    - 早
    - 嗨喽
    - 晚上好
    - hello哈喽
    - hello
    - 在不
    - 早上好
    - 你好
- intent: goodbye
  examples: |
    - 好了，就说这么多了
    - 好了，先这样
    - 下次见
    - 再见
    - 有空再聊
    - 下次再见
    - 拜
    - 886
    - 88
    - bye bye
    - 回头见
    - 先这样吧
    - bye
    - goodbye
    - 下次再聊
    - 拜拜，下次再聊
- intent: search_express
  examples: |
    - 我要查快递
    - 我想查询[圆通](express)快递,单号[YT9372128558055](number)
    - 查快递
    - 帮我差下[中通](express)快递
    - [圆通](express)快递的信息
    - 快递
    - [[中通](express)]([express](express))快递
    - 帮我查下[中通](express)快递，单号[73143086738662](number)
    - 查询快递
    - 帮我查个快递
    - 看下快递
    - 我想知道我的[顺丰](express)快递到哪里了，单号[SF1401090331731](number)
    - 快递号码是[548159201158](number)的[中通](express)快递
    - [中通](express)快递单号为[75417089889012](number)
    - 查下快递
    - 我想知道[中通](express)快递的信息
    - 我需要知道单号[YT5075532844265](number)的[圆通](express)
    - 查下[顺丰](express)快递到哪里了
    - 单号为[75415042420290](number)的[中通](express)信息
    - 帮我查下单号为[YT5078273557325](number)的[圆通](express)快递
    - [中通](express)快递
    - [顺丰](express)单号[SF1406050054883](number)
- synonym: 顺丰
  examples: |
    - 顺丰
    - 顺丰快递
- synonym: 圆通
  examples: |
    - 圆通
    - 圆通快递
- synonym: 中通
  examples: |
    - 中通
    - 中通快递
- lookup: express
  examples: |
    - 顺丰
    - 中通
    - 圆通
